# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_cmt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 450)
        Dialog.setMinimumSize(QtCore.QSize(600, 450))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/resources/logo_s.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"/*QText Edit*/\n"
"QTextEdit {    \n"
"    background-color:  rgb(255, 255, 255);\n"
"    border: 2px solid rgb(242, 142, 66);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/*QPushButton*/\n"
"\n"
"QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 121, 16,200), stop:1 rgba(248, 71, 37,230));\n"
"    color: rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton::hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(228, 90, 16,210), stop:1 rgba(238, 70, 20,230));\n"
"}\n"
"QPushButton::pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgba(253, 52, 13,230);\n"
"}\n"
"\n"
"\n"
"    /* SCROLL BARS*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background:rgb(240, 240, 240);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(232, 115, 11);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background:rgb(232, 115, 11);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(232, 115, 11);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"   background:rgb(240, 240, 240);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background:rgb(232, 115, 11);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(232, 115, 11) ;\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"     background: rgb(232, 115, 11);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_content_cmt = QtWidgets.QTextEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.textEdit_content_cmt.setFont(font)
        self.textEdit_content_cmt.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_content_cmt.setObjectName("textEdit_content_cmt")
        self.verticalLayout.addWidget(self.textEdit_content_cmt)
        self.pushButton_content_cmt = QtWidgets.QPushButton(self.frame)
        self.pushButton_content_cmt.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_content_cmt.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_content_cmt.setFont(font)
        self.pushButton_content_cmt.setObjectName("pushButton_content_cmt")
        self.verticalLayout.addWidget(self.pushButton_content_cmt)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nhập comment"))
        self.textEdit_content_cmt.setPlaceholderText(_translate("Dialog", "Nhập nội dung comment mỗi nick 1 dòng nhé!!!"))
        self.pushButton_content_cmt.setText(_translate("Dialog", "NHẬP NỘI DUNG BÌNH LUẬN"))
import resource_rc
